spring.datasource.url = jdbc:postgresql://localhost:5432/escola
spring.datasource.username = baresi
spring.datasource.password = 123
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.initialization-mode = always
spring.datasource.data = classpath:import.sql
